// <auto-generated />
using System;
using ConsoleAppPracticWork_1_var1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleAppPracticWork_1_var1.Migrations
{
    [DbContext(typeof(WorkerContext))]
    [Migration("20240724220149_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleAppPracticWork_1_var1.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkerJournalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerJournalId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("ConsoleAppPracticWork_1_var1.Model.WorkerJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCameWork")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EscapeCameWork")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("workerJournals");
                });

            modelBuilder.Entity("ConsoleAppPracticWork_1_var1.Model.Employee", b =>
                {
                    b.HasOne("ConsoleAppPracticWork_1_var1.Model.WorkerJournal", "WorkerJournal")
                        .WithMany("Employee")
                        .HasForeignKey("WorkerJournalId");

                    b.Navigation("WorkerJournal");
                });

            modelBuilder.Entity("ConsoleAppPracticWork_1_var1.Model.WorkerJournal", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
